# Generated by Django 3.1.3 on 2020-11-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_meeting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
