# Generated by Django 3.1.3 on 2020-11-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
